ecommerceapp/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
       path('', views.product_list, name='product_list'),
      # path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
       path('product-details', views.product_details, name='product_details'),
       path('checkout/', views.checkout, name='checkout_list'),
       path('cart', views.cart_list, name='cart_list'),
       path('update_item/', views.updateItem, name='update_item'),
        path('process_order/', views.proceOrder, name='process_order'),
    path ('username-valid/', csrf_exempt(views.usernameValidation), name='username-valid'),
    path('email-validation/', csrf_exempt(views.emailValidation), name='email-validation'),
]

eommercesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from ecommerceapp import views as user_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
     path('', include('ecommerceapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerceapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='Customer_image', blank=True)
    email = models.EmailField(max_length=200, blank=True)

    def __str__(self):
        return self.name



LABEL_CHOICES = (
     ('primary', 'primary'),
     ('danger', 'danger'),
     ('secondary', 'secondary')

)

class Product(models.Model):
    label = models.CharField(choices=LABEL_CHOICES, max_length=15)
    product_name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    digital = models.BooleanField(default=False, null=True, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    product_image = models.ImageField(upload_to='product_image', blank=True)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('product_detail', args = [self.id, self.slug])

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_item_total_price(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_total_item(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems ])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=-True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)



    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecommerceapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
# Create your views here.
from .models import *
from django.http import JsonResponse
import json
import datetime
from .utils import cookieCart, cartData
from validate_email import validate_email
# Create your views here.
def usernameValidation(request):
    data = json.loads(request.body)
    username = data['username']
    if not str(username).isalnum():
        return JsonResponse({'username_error': 'Username should only alphanumeric characters'}, status=200)
    if User.objects.filter(username=username).exists():
        return JsonResponse({'username_error': 'Username is already taken,choose another one'}, status=400)
    return JsonResponse({'username_valid': True})

def emailValidation(request):
    data = json.loads(request.body)
    email = data['email']
    if not validate_email(email):
        return JsonResponse({'email_error': 'Email is invalid, set your correct email address'}, status=400)
    if User.objects.filter(email=email):
        return JsonResponse({'email_error': 'Sorry, email address is already used, try another one'}, status=400)
    return JsonResponse("email validatioon", safe=False)


def register(request):
    if request.user.is_authenticated:
        return redirect('product_list')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            fname = request.POST['fname']
            lname = request.POST['lname']
            email = request.POST['email']
            password = request.POST['password']
            context = {'fieldValue': request.POST}
            if not User.objects.filter(username=username).exists():
                if not User.objects.filter(email=email).exists():
                    if len(password)<8:
                        messages.error(request, 'password too short,it have to be minimun 8 characters')
                        return render(request, 'account/register.html', context)
                    if len(username)<5:
                        messages.error(request, 'your username less than 5 characters, try again')
                        return render(request, 'account/register.html', context)
                    user = User.objects.create_user(username=username, email=email)
                    user.first_name = fname
                    user.last_name = lname
                    user.set_password(password)
                    user.save()
                    messages.success(request, 'your account has been successfully created')
                    return redirect('login')
        return render(request, 'account/register.html')





def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order , created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse("it was added", safe=False)

def product_list(request):
    data = cartData(request)
    cartItems = data['cartItems']
    products = Product.objects.all()
    context = { 'products': products , 'cartItems': cartItems}
    return render(request, 'home/product_home.html', context)

def cart_list(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = { 'items': items, 'order':order, 'cartItems':cartItems }
    return render(request, 'home/cart.html', context)

def checkout(request):

    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = { 'items': items, 'order':order, 'cartItems': cartItems }
    return render(request, 'home/checkout.html', context )

def product_details(request):
    return render(request, 'home/product_details.html')

def proceOrder(request):
    #print( 'data:', request.body)
    transction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if  request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        print('user is not log in')
        name = data['form']['name']
        email = data['form']['email']
        cookieData = cookieCart(request)
        items = cookieData['items']
        customer, created = Customer.objects.get_or_create(
             email=email,

        )
        customer.name = name
        customer.save()
        order = Order.objects.create(
            customer=customer,
            complete=False,
        )
        for item in items:
            product = Product.objects.get(id=item['product']['id'])
            orderItem = OrderItem.objects.create(
                product=product,
                order = order,
                quantity=item['quantity']
            )

    total = float(data['form']['total'])
    order.transaction_id = transction_id
    if total == order.get_item_total_price:
        order.complete = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],

        )
    return JsonResponse("payment completed", safe=False)

ecommerceapp/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title> Ecommerce site </title>

    <script type="text/javascript">
      var user =  '{{ request.user }}'

      function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
	var csrftoken = getToken('csrftoken')

// get guest user cookie
 function getCookie(name){
	 var cookieArr = document.cookie.split(";");
	 for(var i = 0; i < cookieArr.length; i++){
		 var cookiePair = cookieArr[i].split("=");
		 if(name == cookiePair[0].trim()){
			 return decodeURIComponent(cookiePair[1]);
		 }
	 }
	 return null;
 }
 var cart = JSON.parse(getCookie('cart'))
 console.log('cart:', cart)
 if( cart == undefined){
	 cart = {}
	 console.log('cart was created for guest user')
	 document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
 }
    </script>

  </head>
  <body class="body_section">

    {% block body %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/regvalidation.js' %}"></script>
  </body>
</html>

ecommerceapp/templates/home/cart.html
{% extends 'home/base.html' %}
{% block body %}
{% include 'separate/navbar.html' %}
<div class="container">
<div class="row justify-content-center">
  <div class="col-md-10">


  <table class="table table-bordered table_background">
    <thead>

      <tr>

        <th scope="col">Product</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>

        <td><img src="{{ item.product.product_image.url }}" alt="" class="item_image"></td>
        <td>{{item.product.product_name }}</td>
        <td> <span  data-product={{ item.product.id}} data-action="add" class="update-cart"><i class="fas fa-plus"></i></span>{{ item.quantity }}

       <span  data-product={{ item.product.id}} data-action="remove" class="update-cart btn btn-sm"><i class="fas fa-minus"></i></span>
        </td>
        <td>${{ item.get_total }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 card ">
<div class="card-body">

  <div class="text-center">
    <a href="{% url 'product_list' %}" class="btn btn-primary m-3"> Continue Shipping </a>
  </div>
  <table class="table">
<tbody>
  <tr>
    <td><strong>Total Items : {{order.get_total_item }}</strong></td>
    <td><strong>Total Price : ${{order.get_item_total_price }}</strong></td>
    <td><a href="{% url 'checkout_list' %}" class="btn btn-success"> Checkout</a></td>
  </tr>

</tbody>

</table>
</div>

      </div>
    </div>
  </div>


{% endblock %}

ecommerceapp/templates/home/checkout.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
{% include 'separate/navbar.html' %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
<div class="card">
  <div class="card-body" id="form-wrapper">

            <form id="form">
                <div id="user-info">
        <div class="form-group">
        <input type="text" name="name" class="form-control"  placeholder="Name here" required>
        </div>
        <div class="form-group">
    <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email" required>
        </div>
          </div>


          <div id="shipping-info">
            <h2>Shipping information</h2>
            <div class="form-group">
              <input type="text" class="formfield" name="address" placeholder="address...." required>
              <input type="text" class="formfield" name="city" placeholder="city....." required>
              <input type="text" class="formfield" name="state" placeholder="state...." required>
              <input type="text" class="formfield" name="zipcode" placeholder="zipcode....." required>
            </div>
          </div>
          <button type="submit" id="form-button" class="btn btn-outline-primary btn-block">Continue</button>

          <div class="hidden" id="payment-info">
              <small>Paymant</small> <button id="make-payment" type="submit" class="btn btn-outline-secondary">Make Payment</button>
          </div>

      </form>

  </div>
</div>

    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h3>Your Order</h3>
          <table class="table table-bordered table_background">
            <thead>

              <tr>

                <th scope="col">Product</th>
                <th scope="col">Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              {% for item in items %}
              <tr>

                <td><img src="{{ item.product.product_image.url }}" alt="" class="item_image"></td>
                <td>{{item.product.product_name }}</td>
              <td>{{ item.quantity }} </td>
                <td>${{ item.get_total }}</td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan="2">Total</td>
                <td><strong>{{order.get_total_item }}</strong></td>
                <td><strong name="total">${{order.get_item_total_price }}</strong></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
      var shipping = '{{ order.shipping }}'
      var total = '{{ order.get_item_total_price}}'
          if(shipping == 'False'){
            document.getElementById('shipping-info').innerHTML = ''
          }
          if(user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
          }
          if(shipping == 'False' && user != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add("hidden");
            document.getElementById('payment-info').classList.remove("hidden");
          }

      var form = document.getElementById('form')
      form.addEventListener('submit', function(e){
        e.preventDefault()
        console.log('form submitted')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')

      })
      document.getElementById('make-payment').addEventListener('click', function(e){
      submitFormData()
      })
      function submitFormData(){
            var userFormData = {
              'name': null,
              'email': null,
              'total': total,
            }
            var shippingInfo = {
              'address': null,
              'city': null,
              'state': null,
              'zipcode': null,
            }
      if(shipping != 'False'){
        shippingInfo.address = form.address.value
        shippingInfo.city = form.city.value
        shippingInfo.state = form.state.value
        shippingInfo.zipcode = form.zipcode.value
      }
      if( user == 'AnonymousUser'){
        userFormData.name = form.name.value
        userFormData.email = form.email.value

      }
    var url = '/process_order/'
    fetch(url, {
      method : 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrftoken,
      },
      body : JSON.stringify({ 'form': userFormData, 'shipping': shippingInfo})
    })
    .then((response) => response.json())
    .then((data) =>{
      console.log('success:', data)
      alert(' transaction complated');
      cart = {}
      document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
      window.location.href = "{% url 'product_list' %}"
    })

}
</script>
{% endblock %}

ecommerceapp/templates/home/product_details.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
{% include 'separate/navbar.html' %}
<div class="container card">
  <div class="row card-body justify-content-center">

    <div class="col-md-4">
      <img src="{% static 'img/watch.jpg' %}" class="img-fluid product_image" alt="Responsive image">
    </div>
    <div class="col-md-6">
      <span></span>
      <p>
      There are many variations of passages of Lorem Ipsum available,
      but the majority have suffered alteration in some form, by injected humour,
       or randomised words which don't look even slightly believable.
    to generate Lorem Ipsum which looks reasonable.
  our, or non-characteristic words etc.</p>
    </div>
  </div>
  </div>

{% endblock %}

ecommerceapp/templates/home/product_home.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
{% include 'separate/navbar.html' %}
<div class="container">
{% for product in products %}
  <div class="card product_box">
    <div class="card-body">
<a href="{% url 'product_details' %}">
      <img src="{{ product.product_image.url }}" class="img-fluid product_image" alt="Responsive image">
      <hr>
  <h5>{{ product.product_name }}</h5>
    <p><strong>${{product.price }}</strong> <span class="badge badge-{{ product.get_label_display }}">new</span> </p>

  </a>
  <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
    </div>

  </div>
{% endfor %}

</div>
{% endblock %}